/**
 * SMANV EduERP Realistic Enterprise Mock Data
 * Developed by SMANV Info Tech Private Limited
 */

import {
  User,
  Organization,
  Student,
  Staff,
  ClassSession,
  Assignment,
  Examination,
  FeeRecord,
  NotificationItem,
  AIInsight,
  RecentActivity,
  Announcement,
  AdmissionApplication,
} from '../types';

export const MOCK_ORGANIZATION: Organization = {
  id: 'org-101',
  name: 'SMANV International Academy & College',
  type: 'school',
  code: 'SMANV-DEL-01',
  email: 'admin@smanvedu.org',
  phone: '+91 11 4567 8900',
  address: 'Plot 42, Institutional Area, Knowledge Park II',
  city: 'New Delhi',
  state: 'Delhi',
  pincode: '110075',
  studentCount: 2450,
  staffCount: 182,
  establishedYear: 2008,
  academicYear: '2026-2027',
};

export const DEMO_USERS: Record<string, User> = {
  super_admin: {
    id: 'user-super-01',
    name: 'Dr. Arvind Mehta',
    email: 'superadmin@smanv.com',
    role: 'super_admin',
    organizationId: 'org-smanv-hq',
    organizationName: 'SMANV Info Tech Private Limited',
    designation: 'Enterprise Platform Director',
    phone: '+91 98111 00111',
  },
  org_admin: {
    id: 'user-admin-01',
    name: 'Dr. Rajesh Sharma',
    email: 'principal@smanvedu.org',
    role: 'org_admin',
    organizationId: 'org-101',
    organizationName: 'SMANV group of institutions',
    designation: 'Principal & Chief Administrator',
    phone: '+91 98222 11222',
  },
  staff: {
    id: 'user-staff-01',
    name: 'Prof. Priya Nair',
    email: 'priya.nair@smanvedu.org',
    role: 'staff',
    organizationId: 'org-101',
    organizationName: 'SMANV group of institutions',
    designation: 'Head of Department (Physics)',
    department: 'Science & Technology',
    phone: '+91 98333 22333',
  },
  student: {
    id: 'user-student-01',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@smanvedu.org',
    role: 'student',
    organizationId: 'org-101',
    organizationName: 'SMANV group of institutions',
    grade: 'Grade 11',
    section: 'A',
    studentId: 'STU-2026-11024',
    phone: '+91 98444 33444',
  },
  parent: {
    id: 'user-parent-01',
    name: 'Vikram Sharma',
    email: 'vikram.parent@gmail.com',
    role: 'parent',
    organizationId: 'org-101',
    organizationName: 'SMANV group of institutions',
    studentId: 'STU-2026-11024',
    phone: '+91 98555 44555',
  },
  finance: {
    id: 'user-finance-01',
    name: 'Sunil Verma',
    email: 'accounts@smanvedu.org',
    role: 'finance',
    organizationId: 'org-101',
    organizationName: 'SMANV International Academy',
    designation: 'Senior Accounts & Bursar Officer',
    phone: '+91 98666 55666',
  },
};

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'STU-2026-11024',
    name: 'Aarav Sharma',
    rollNumber: '11A-24',
    grade: 'Grade 11',
    section: 'A',
    gender: 'Male',
    dob: '2009-08-14',
    bloodGroup: 'B+',
    parentName: 'Vikram Sharma',
    parentPhone: '+91 98555 44555',
    parentEmail: 'vikram.parent@gmail.com',
    address: 'B-402, Green Valley Enclave, Sector 18, New Delhi',
    attendanceRate: 95.8,
    feeStatus: 'Paid',
    pendingAmount: 0,
    qrCode: 'SMANV-STU-11024-2026',
  },
  {
    id: 'STU-2026-11025',
    name: 'Ananya Iyer',
    rollNumber: '11A-05',
    grade: 'Grade 11',
    section: 'A',
    gender: 'Female',
    dob: '2009-11-22',
    bloodGroup: 'O+',
    parentName: 'Karthik Iyer',
    parentPhone: '+91 98777 66777',
    parentEmail: 'karthik.iyer@gmail.com',
    address: 'Villa 12, Royal Palms, New Delhi',
    attendanceRate: 98.2,
    feeStatus: 'Paid',
    pendingAmount: 0,
    qrCode: 'SMANV-STU-11025-2026',
  },
  {
    id: 'STU-2026-10012',
    name: 'Rohan Deshmukh',
    rollNumber: '10B-18',
    grade: 'Grade 10',
    section: 'B',
    gender: 'Male',
    dob: '2010-04-10',
    bloodGroup: 'A+',
    parentName: 'Sanjay Deshmukh',
    parentPhone: '+91 98888 77888',
    parentEmail: 'sanjay.d@gmail.com',
    address: 'Flat 301, Rosewood Heights, New Delhi',
    attendanceRate: 88.4,
    feeStatus: 'Pending',
    pendingAmount: 18500,
    qrCode: 'SMANV-STU-10012-2026',
  },
  {
    id: 'STU-2026-10015',
    name: 'Diya Patel',
    rollNumber: '10A-11',
    grade: 'Grade 10',
    section: 'A',
    gender: 'Female',
    dob: '2010-02-18',
    bloodGroup: 'AB+',
    parentName: 'Bhavin Patel',
    parentPhone: '+91 98999 88999',
    parentEmail: 'bhavin.p@gmail.com',
    address: 'Tower C, Lotus Court, New Delhi',
    attendanceRate: 96.0,
    feeStatus: 'Paid',
    pendingAmount: 0,
    qrCode: 'SMANV-STU-10015-2026',
  },
  {
    id: 'STU-2026-09044',
    name: 'Kabir Singhania',
    rollNumber: '09C-22',
    grade: 'Grade 9',
    section: 'C',
    gender: 'Male',
    dob: '2011-06-30',
    bloodGroup: 'O-',
    parentName: 'Rajesh Singhania',
    parentPhone: '+91 98123 45678',
    parentEmail: 'rajesh.singh@gmail.com',
    address: 'Sector 23, Dwarka, New Delhi',
    attendanceRate: 72.5,
    feeStatus: 'Overdue',
    pendingAmount: 27500,
    qrCode: 'SMANV-STU-09044-2026',
  },
  {
    id: 'STU-2026-12001',
    name: 'Meera Kapoor',
    rollNumber: '12A-01',
    grade: 'Grade 12',
    section: 'A',
    gender: 'Female',
    dob: '2008-09-12',
    bloodGroup: 'A-',
    parentName: 'Harish Kapoor',
    parentPhone: '+91 98234 56789',
    parentEmail: 'h.kapoor@gmail.com',
    address: 'C-7, Vasant Vihar, New Delhi',
    attendanceRate: 99.1,
    feeStatus: 'Paid',
    pendingAmount: 0,
    qrCode: 'SMANV-STU-12001-2026',
  },
];

export const MOCK_STAFF: Staff[] = [
  {
    id: 'STF-001',
    name: 'Prof. Priya Nair',
    employeeCode: 'EMP-PHY-01',
    department: 'Science & Technology',
    designation: 'HOD & Senior Physics Faculty',
    email: 'priya.nair@smanvedu.org',
    phone: '+91 98333 22333',
    qualification: 'M.Sc., Ph.D. (Physics)',
    joiningDate: '2016-07-15',
    status: 'In Class',
    attendanceRate: 98.5,
    subjects: ['Advanced Physics', 'Quantum Basics', 'Applied Mechanics'],
  },
  {
    id: 'STF-002',
    name: 'Dr. Alok Verma',
    employeeCode: 'EMP-MAT-04',
    department: 'Mathematics',
    designation: 'Senior Faculty',
    email: 'alok.verma@smanvedu.org',
    phone: '+91 98111 22444',
    qualification: 'Ph.D. (Applied Mathematics)',
    joiningDate: '2018-04-10',
    status: 'On Duty',
    attendanceRate: 96.0,
    subjects: ['Calculus', 'Linear Algebra', 'Statistics'],
  },
  {
    id: 'STF-003',
    name: 'Ms. Sunita Rao',
    employeeCode: 'EMP-ENG-02',
    department: 'Languages & Humanities',
    designation: 'Senior English Educator',
    email: 'sunita.rao@smanvedu.org',
    phone: '+91 98222 33555',
    qualification: 'M.A., M.Ed.',
    joiningDate: '2019-08-01',
    status: 'In Class',
    attendanceRate: 97.4,
    subjects: ['English Literature', 'Communication Skills'],
  },
  {
    id: 'STF-004',
    name: 'Mr. Devendra Joshi',
    employeeCode: 'EMP-CS-01',
    department: 'Computer Science & AI',
    designation: 'Lead AI Lab Instructor',
    email: 'dev.joshi@smanvedu.org',
    phone: '+91 98444 55777',
    qualification: 'M.Tech (Computer Science)',
    joiningDate: '2021-02-15',
    status: 'On Duty',
    attendanceRate: 99.0,
    subjects: ['Python & Data Science', 'Artificial Intelligence', 'Cybersecurity'],
  },
  {
    id: 'STF-005',
    name: 'Dr. Shalini Saxena',
    employeeCode: 'EMP-BIO-03',
    department: 'Science & Technology',
    designation: 'Associate Professor',
    email: 'shalini.saxena@smanvedu.org',
    phone: '+91 98555 66888',
    qualification: 'Ph.D. (Biotechnology)',
    joiningDate: '2017-11-20',
    status: 'On Leave',
    attendanceRate: 92.1,
    subjects: ['Cellular Biology', 'Genetics'],
  },
];

export const MOCK_CLASS_SESSIONS: ClassSession[] = [
  {
    id: 'CS-01',
    period: 1,
    startTime: '08:30 AM',
    endTime: '09:15 AM',
    subject: 'Physics (Mechanics)',
    grade: 'Grade 11',
    section: 'A',
    room: 'Lab 302',
    teacherName: 'Prof. Priya Nair',
    status: 'Completed',
  },
  {
    id: 'CS-02',
    period: 2,
    startTime: '09:20 AM',
    endTime: '10:05 AM',
    subject: 'Mathematics (Calculus)',
    grade: 'Grade 11',
    section: 'A',
    room: 'Hall 104',
    teacherName: 'Dr. Alok Verma',
    status: 'Ongoing',
  },
  {
    id: 'CS-03',
    period: 3,
    startTime: '10:20 AM',
    endTime: '11:05 AM',
    subject: 'AI & Data Systems',
    grade: 'Grade 11',
    section: 'A',
    room: 'Computer Lab 2',
    teacherName: 'Mr. Devendra Joshi',
    status: 'Upcoming',
  },
  {
    id: 'CS-04',
    period: 4,
    startTime: '11:10 AM',
    endTime: '11:55 AM',
    subject: 'English Literature',
    grade: 'Grade 11',
    section: 'A',
    room: 'Room 201',
    teacherName: 'Ms. Sunita Rao',
    status: 'Upcoming',
  },
];

export const MOCK_ASSIGNMENTS: Assignment[] = [
  {
    id: 'ASN-101',
    title: 'Electromagnetic Induction Problem Set',
    subject: 'Physics',
    grade: 'Grade 11',
    section: 'A',
    dueDate: '2026-09-10',
    assignedDate: '2026-09-02',
    totalMarks: 50,
    submissionsCount: 28,
    totalStudents: 32,
    status: 'Active',
    description: 'Solve numerical problems 1-15 from Chapter 6 and submit working sheets.',
  },
  {
    id: 'ASN-102',
    title: 'Differential Calculus Applications Essay',
    subject: 'Mathematics',
    grade: 'Grade 11',
    section: 'A',
    dueDate: '2026-09-12',
    assignedDate: '2026-09-03',
    totalMarks: 30,
    submissionsCount: 14,
    totalStudents: 32,
    status: 'Active',
    description: 'Case study on rate of change in aerospace engineering systems.',
  },
  {
    id: 'ASN-103',
    title: 'Python Neural Network Classifier Lab',
    subject: 'Computer Science & AI',
    grade: 'Grade 11',
    section: 'A',
    dueDate: '2026-08-30',
    assignedDate: '2026-08-20',
    totalMarks: 100,
    submissionsCount: 32,
    totalStudents: 32,
    status: 'Graded',
    description: 'Build a 3-layer neural network from scratch using NumPy.',
  },
];

export const MOCK_EXAMINATIONS: Examination[] = [
  {
    id: 'EXM-2026-T1-01',
    title: 'Mid-Term Examination: Physics',
    subject: 'Physics',
    grade: 'Grade 11',
    date: '2026-09-22',
    startTime: '09:00 AM',
    endTime: '12:00 PM',
    room: 'Main Auditorium Hall B',
    maxMarks: 100,
    passPercentage: 40,
    status: 'Scheduled',
  },
  {
    id: 'EXM-2026-T1-02',
    title: 'Mid-Term Examination: Mathematics',
    subject: 'Mathematics',
    grade: 'Grade 11',
    date: '2026-09-24',
    startTime: '09:00 AM',
    endTime: '12:00 PM',
    room: 'Main Auditorium Hall B',
    maxMarks: 100,
    passPercentage: 40,
    status: 'Scheduled',
  },
  {
    id: 'EXM-2026-T1-03',
    title: 'Mid-Term Examination: Computer Science',
    subject: 'Computer Science',
    grade: 'Grade 11',
    date: '2026-09-26',
    startTime: '09:00 AM',
    endTime: '12:00 PM',
    room: 'Lab 1 & 2',
    maxMarks: 100,
    passPercentage: 40,
    status: 'Scheduled',
  },
];

export const MOCK_FEES: FeeRecord[] = [
  {
    id: 'FEE-2026-8801',
    receiptNumber: 'REC-2026-0982',
    studentId: 'STU-2026-11024',
    studentName: 'Aarav Sharma',
    grade: 'Grade 11',
    section: 'A',
    category: 'Tuition',
    amount: 32500,
    dueDate: '2026-09-01',
    paidDate: '2026-08-28',
    status: 'Paid',
    paymentMode: 'Online',
    qrCode: 'SMANV-FEE-REC-0982-VERIFIED',
  },
  {
    id: 'FEE-2026-8802',
    receiptNumber: 'REC-2026-0983',
    studentId: 'STU-2026-10012',
    studentName: 'Rohan Deshmukh',
    grade: 'Grade 10',
    section: 'B',
    category: 'Tuition',
    amount: 18500,
    dueDate: '2026-09-05',
    status: 'Pending',
    qrCode: 'SMANV-FEE-REC-0983-PENDING',
  },
  {
    id: 'FEE-2026-8803',
    receiptNumber: 'REC-2026-0984',
    studentId: 'STU-2026-09044',
    studentName: 'Kabir Singhania',
    grade: 'Grade 9',
    section: 'C',
    category: 'Annual',
    amount: 27500,
    dueDate: '2026-08-15',
    status: 'Overdue',
    qrCode: 'SMANV-FEE-REC-0984-OVERDUE',
  },
  {
    id: 'FEE-2026-8804',
    receiptNumber: 'REC-2026-0985',
    studentId: 'STU-2026-12001',
    studentName: 'Meera Kapoor',
    grade: 'Grade 12',
    section: 'A',
    category: 'Laboratory',
    amount: 12000,
    dueDate: '2026-09-15',
    paidDate: '2026-09-03',
    status: 'Paid',
    paymentMode: 'UPI',
    qrCode: 'SMANV-FEE-REC-0985-VERIFIED',
  },
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ai-ins-01',
    title: 'Attendance Risk Detected',
    type: 'attendance',
    severity: 'warning',
    description: '14 students in Grade 9-C have dipped below the 75% mandatory threshold over the last 14 days.',
    recommendation: 'Send automated SMS notifications to guardians and schedule counseling with the class mentor.',
    metric: '14 At-Risk',
    actionText: 'Review Grade 9-C Roster',
    actionRoute: '/attendance',
  },
  {
    id: 'ai-ins-02',
    title: 'Fee Recovery Acceleration',
    type: 'fee',
    severity: 'info',
    description: 'Term 2 fee collection is currently at 86.4%, which is 7.2% faster than the corresponding period last academic year.',
    recommendation: 'Issue friendly WhatsApp reminders to 48 families with dues maturing on Sept 10.',
    metric: '₹1.84 Cr Collected',
    actionText: 'Send Fee Reminders',
    actionRoute: '/fees',
  },
  {
    id: 'ai-ins-03',
    title: 'Exam Performance Predictor',
    type: 'performance',
    severity: 'success',
    description: 'Class 11-A Physics average simulated score is projected at 82.4% based on continuous unit tests and lab records.',
    recommendation: 'Deploy advanced elective challenges for top 12 percentile performers.',
    metric: '82.4% Projected',
    actionText: 'Open Academics',
    actionRoute: '/academics',
  },
];

export const MOCK_ACTIVITIES: RecentActivity[] = [
  {
    id: 'act-01',
    title: 'Fee receipt #REC-2026-0985 generated for Meera Kapoor (Grade 12-A)',
    timestamp: '12 mins ago',
    user: 'Accounts Bursar Sunil Verma',
    type: 'fee',
    icon: 'receipt',
  },
  {
    id: 'act-02',
    title: 'Prof. Priya Nair submitted internal assessment marks for Class 11-A',
    timestamp: '45 mins ago',
    user: 'Prof. Priya Nair',
    type: 'academic',
    icon: 'school',
  },
  {
    id: 'act-03',
    title: 'Daily attendance registered: 2,328 / 2,450 students present (95.0%)',
    timestamp: '2 hours ago',
    user: 'Automated RFID & Biometric Gate',
    type: 'attendance',
    icon: 'finger-print',
  },
  {
    id: 'act-04',
    title: 'New Admission application #ADM-2026-088 received for Grade 11 Science',
    timestamp: '3 hours ago',
    user: 'Admissions Portal',
    type: 'admission',
    icon: 'person-add',
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-01',
    title: 'Annual SMANV Inter-School Science & AI Exhibition 2026',
    content: 'Registration for project prototypes is now live. All Grade 9-12 students are encouraged to submit project briefs by Sept 18.',
    date: 'Sept 05, 2026',
    author: 'Principal Dr. Rajesh Sharma',
    priority: 'High',
    targetRoles: ['org_admin', 'staff', 'student', 'parent'],
  },
  {
    id: 'ann-02',
    title: 'Parent-Teacher Conference (PTC) Schedule - Term 1',
    content: 'PTC will be held on Saturday, Sept 28, from 09:00 AM to 02:00 PM. Digital slot booking is available under Academics.',
    date: 'Sept 04, 2026',
    author: 'Academic Dean',
    priority: 'Normal',
    targetRoles: ['staff', 'parent'],
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'SMANV AI Alert: Attendance Threshold',
    message: 'Grade 9-C cumulative attendance has declined by 3.2% this week.',
    category: 'AI Alerts',
    timestamp: '10 mins ago',
    isRead: false,
    priority: 'high',
    actionRoute: '/attendance',
  },
  {
    id: 'notif-02',
    title: 'Fee Payment Received',
    message: 'Payment of ₹12,000 received for Receipt #REC-2026-0985 (Meera Kapoor).',
    category: 'Fees',
    timestamp: '1 hour ago',
    isRead: false,
    priority: 'medium',
    actionRoute: '/fees',
  },
  {
    id: 'notif-03',
    title: 'New Assignment Published',
    message: 'Electromagnetic Induction Problem Set assigned for Grade 11-A.',
    category: 'Academics',
    timestamp: '3 hours ago',
    isRead: true,
    priority: 'low',
    actionRoute: '/assignments',
  },
  {
    id: 'notif-04',
    title: 'Mid-Term Exam Datesheet Released',
    message: 'Official timetable for Mid-Term Examinations is now available for download.',
    category: 'Academics',
    timestamp: 'Yesterday',
    isRead: true,
    priority: 'medium',
    actionRoute: '/examinations',
  },
];

export const MOCK_ADMISSIONS: AdmissionApplication[] = [
  {
    id: 'ADM-2026-088',
    applicantName: 'Ishaan Deshmukh',
    gradeApplying: 'Grade 11 (Science)',
    parentName: 'Manoj Deshmukh',
    parentPhone: '+91 98765 12345',
    appliedDate: '2026-09-04',
    stage: 'Screening',
    previousSchool: 'Modern Vidya Mandir, Delhi (94.2% in Class 10)',
    notes: 'National Science Olympiad rank holder.',
  },
  {
    id: 'ADM-2026-087',
    applicantName: 'Sanya Mukherjee',
    gradeApplying: 'Grade 9',
    parentName: 'Dr. Debashis Mukherjee',
    parentPhone: '+91 98876 23456',
    appliedDate: '2026-09-02',
    stage: 'Interview',
    previousSchool: 'DPS RK Puram (89.5%)',
    notes: 'Interview scheduled for Sept 08 with Academic Panel.',
  },
  {
    id: 'ADM-2026-086',
    applicantName: 'Tanmay Rathore',
    gradeApplying: 'Grade 11 (Commerce & AI)',
    parentName: 'Alok Rathore',
    parentPhone: '+91 98987 34567',
    appliedDate: '2026-08-28',
    stage: 'Offered',
    previousSchool: 'Heritage School, Gurgaon (91.0%)',
    notes: 'Offer letter dispatched. Awaiting fee confirmation.',
  },
];
