# Generated by Django 6.0.6 on 2026-09-06 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('attendance', 'Attendance'), ('fee', 'Fee'), ('performance', 'Performance'), ('workload', 'Workload')], default='attendance', max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('success', 'Success')], default='info', max_length=20)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('metric', models.CharField(blank=True, max_length=100, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('action_route', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
