# Generated by Django 6.0.6 on 2026-09-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('examination', 'student')},
        ),
    ]
