# Generated by Django 6.0.6 on 2026-09-06 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Tuition', 'Tuition'), ('Transport', 'Transport'), ('Laboratory', 'Laboratory'), ('Sports', 'Sports'), ('Annual', 'Annual')], default='Tuition', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('payment_mode', models.CharField(blank=True, choices=[('Online', 'Online'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('UPI', 'UPI')], max_length=30, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
