# Generated by Django 6.0.6 on 2026-09-06 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('attendance', 'Attendance'), ('financial', 'Financial'), ('admissions', 'Admissions')], default='academic', max_length=30)),
                ('value', models.CharField(max_length=50)),
                ('change', models.CharField(default='+0.0%', max_length=50)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('period', models.CharField(default='This Month', max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_metrics', to='organizations.organization')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
