# Generated by Django 6.0.6 on 2026-09-06 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Official name of the institution', max_length=255)),
                ('type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('institute', 'Institute')], default='school', help_text='Type of institution (school/college/university/institute)', max_length=50)),
                ('code', models.CharField(blank=True, help_text='Short institutional code (e.g. SMANV)', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Official contact email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=25, null=True)),
                ('address', models.TextField(blank=True, help_text='Campus street address', null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('subscription_plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], db_index=True, default='active', max_length=50)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('established_year', models.PositiveIntegerField(default=2026)),
                ('academic_year', models.CharField(default='2026-2027', max_length=25)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
